name: howtocook
description: "智能菜谱助手 - 基于 AI 的跨平台菜谱管理和推荐应用"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # 状态管理
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.5.0

  # 本地存储
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.4.1
  path_provider: ^2.1.5

  # 网络请求
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0

  # 路由
  go_router: ^14.6.2

  # 数据模型
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # 图片处理
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0

  # 环境变量
  flutter_dotenv: ^5.2.1

  # UI 组件
  flutter_markdown: ^0.7.4+1
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 代码生成
  build_runner: ^2.4.13
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  hive_generator: ^2.0.1

  # 代码规范
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # 资源文件
  assets:
    - .env
    - assets/images/
    - assets/recipes/
    - assets/tips/
