name: howtocook
description: "智能菜谱助手 - 基于 AI 的跨平台菜谱管理和推荐应用"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # 状态管理
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.5.0

  # 本地存储
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path: ^1.9.0

  # 网络请求
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0

  # 路由
  go_router: ^14.6.2

  # 数据模型
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  crypto: ^3.0.3
  html_unescape: ^2.0.0

  # 图片处理
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0

  # 环境变量
  flutter_dotenv: ^5.2.1

  # UI 组件
  flutter_markdown: ^0.7.4+1
  flutter_spinkit: ^5.2.1
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1

  # 分享功能
  share_plus: ^10.1.2
  qr_flutter: ^4.1.0
  screenshot: ^3.0.0
  archive: ^3.6.1  # GZIP 压缩
  gal: ^2.3.0  # 保存到相册（替代 image_gallery_saver）
  mobile_scanner: ^5.2.3  # 二维码扫描（相机实时扫描）
  opencv_dart: ^1.4.3  # OpenCV for Dart（WeChatQRCode 强力扫描）
  image: ^4.3.0  # 图片处理（裁剪、缩放等）

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 代码生成
  build_runner: ^2.4.13
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  hive_generator: ^2.0.1

  # 代码规范
  flutter_lints: ^5.0.0

  # 测试工具
  image: ^4.3.0  # 图片处理和分析

  # 图标生成
  flutter_launcher_icons: ^0.14.1

# 应用图标配置
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/howtocook.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/howtocook.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  # 资源文件
  assets:
    - .env
    - assets/icon/
    - assets/manifest.json
    # WeChat QRCode models
    - assets/models/wechat_qrcode/
    # covers 封面图（AI 生成，打包到 APK）
    - assets/covers/aquatic/
    - assets/covers/breakfast/
    - assets/covers/condiment/
    - assets/covers/dessert/
    - assets/covers/drink/
    - assets/covers/meat_dish/
    - assets/covers/semi-finished/
    - assets/covers/soup/
    - assets/covers/staple/
    - assets/covers/vegetable_dish/
    # recipes 子目录
    - assets/recipes/aquatic/
    - assets/recipes/breakfast/
    - assets/recipes/condiment/
    - assets/recipes/dessert/
    - assets/recipes/drink/
    - assets/recipes/meat_dish/
    - assets/recipes/semi-finished/
    - assets/recipes/soup/
    - assets/recipes/staple/
    - assets/recipes/vegetable_dish/
    # tips 子目录
    - assets/tips/advanced/
    - assets/tips/general/
    - assets/tips/learn/
